"""dots

Revision ID: 56601ab1aa80
Revises: 78110ff8bd57
Create Date: 2023-08-31 21:14:42.786654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56601ab1aa80'
down_revision = '78110ff8bd57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dots_id'), 'dots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dots_id'), table_name='dots')
    op.drop_table('dots')
    # ### end Alembic commands ###
